In [1]:
import pandas as pd

df = pd.read_csv('Housing.csv')

print(df.head())
print(df.dtypes) 

      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
price                int64
area                 int64
bedrooms             int64
bathrooms         

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

print(df.columns)
df.columns = df.columns.str.strip()
# One-hot encoding for 'furnishingstatus' column
df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True)


Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('price', axis=1)  # Features: all columns except 'price'
y = df['price']               # Target: 'price' column

# Assuming df is your DataFrame
# Convert binary columns
binary_columns = ['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
for col in binary_columns:
    df[col] = df[col].map({'yes': 1, 'no': 0})

# Define X and y
X = df.drop('price', axis=1)  # Features
y = df['price']               # Target

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
log_reg = LogisticRegression(max_iter=1000, C=1.0)
log_reg.fit(X_train_scaled, y_train)


LogisticRegression(max_iter=1000)

In [4]:
svc = SVC()
knn = KNeighborsClassifier()

linear_svc = LinearSVC(dual=False, max_iter=1000)
linear_svc.fit(X_train, y_train)
svc.fit(X_train, y_train)
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [5]:
log_reg_predictions = log_reg.predict(X_test)
linear_svc_predictions = linear_svc.predict(X_test)
svc_predictions = svc.predict(X_test)
knn_predictions = knn.predict(X_test)


/Users/ayseasliilhan/anaconda3/lib/python3.11/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [6]:
from sklearn.metrics import accuracy_score, confusion_matrix

print("Logistic Regression Accuracy:", accuracy_score(y_test, log_reg_predictions))
print("Linear SVC Accuracy:", accuracy_score(y_test, linear_svc_predictions))
print("SVC Accuracy:", accuracy_score(y_test, svc_predictions))
print("KNN Accuracy:", accuracy_score(y_test, knn_predictions))

print("Confusion Matrix (Logistic Regression):\n", confusion_matrix(y_test, log_reg_predictions))


Logistic Regression Accuracy: 0.0
Linear SVC Accuracy: 0.009174311926605505
SVC Accuracy: 0.009174311926605505
KNN Accuracy: 0.009174311926605505
Confusion Matrix (Logistic Regression):
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# Assuming df is your DataFrame
X = df.drop('price', axis=1).values
y = df['price'].values

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert data types to float32 for TensorFlow compatibility
X_scaled = X_scaled.astype(np.float32)
y = y.astype(np.float32)

# TensorFlow operations
tensor_X = tf.convert_to_tensor(X_scaled)

# Reshape y to a 2D tensor
tensor_y = tf.convert_to_tensor(y.reshape(-1, 1))  # Reshape to [545, 1]

# Perform matrix multiplication
result = tf.matmul(tensor_X, tensor_y)  # This should now work

# Do something with the result
print(result)


2023-12-05 12:47:18.746647: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [545,13], In[1]: [545,1] [Op:MatMul]